In [1]:
import spacy
import pandas as pd

# 1. Download the model in your terminal
## Make sure your virtual environment is activated, then run:

```python3 -m spacy download en_core_web_sm```

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [4]:
spacy_doc = nlp(emma_ja)

In [5]:
pos_df = pd.DataFrame(columns=["token", "pos_tag"])

In [6]:
for token in spacy_doc:
    pos_df = pd.concat(
        [
            pos_df, pd.DataFrame.from_records([{"token": token.text, "pos_tag":token.pos_}])
        ],ignore_index=True
    )

In [7]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [8]:
pos_df_counts = pos_df.groupby(["token", "pos_tag"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)

In [9]:
pos_df_counts.head(10)

    token pos_tag  counts
88     of     ADP      14
49    had     AUX       9
54    her    PRON       9
111   the     DET       8
6     and   CCONJ       8
0       a     DET       6
114    to    PART       5
61     in     ADP       4
13   been     AUX       4
120  very     ADV       4

In [10]:
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])["token"].count().sort_values(ascending=False)

In [11]:
pos_df_poscounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [12]:
nouns = pos_df_counts[pos_df_counts.pos_tag == "NOUN"]

In [13]:
nouns

           token pos_tag  counts
48     governess    NOUN       3
46        friend    NOUN       3
130        years    NOUN       2
35          emma    NOUN       2
28     daughters    NOUN       2
103      sisters    NOUN       2
82        mother    NOUN       2
89        office    NOUN       1
78      mistress    NOUN       1
75      mildness    NOUN       1
94        period    NOUN       1
95         place    NOUN       1
96   remembrance    NOUN       1
129        world    NOUN       1
126        woman    NOUN       1
121          vex    NOUN       1
109       temper    NOUN       1
108      taylors    NOUN       1
100       shadow    NOUN       1
97     restraint    NOUN       1
74      marriage    NOUN       1
66      judgment    NOUN       1
32      distress    NOUN       1
31   disposition    NOUN       1
27   consequence    NOUN       1
22      caresses    NOUN       1
18     blessings    NOUN       1
11     authority    NOUN       1
1      affection    NOUN       1
64      intimacy    NOUN       1
59         house    NOUN       1
58          home    NOUN       1
43        father    NOUN       1
42        family    NOUN       1
40     existence    NOUN       1

In [14]:
adj = pos_df_counts[pos_df_counts.pos_tag == "ADJ"]

In [15]:
adj.head(10)

           token pos_tag  counts
70        little     ADJ       2
91           own     ADJ       1
86       nominal     ADJ       1
79          more     ADJ       1
102        short     ADJ       1
98          rich     ADJ       1
34         early     ADJ       1
26   comfortable     ADJ       1
25        clever     ADJ       1
16          best     ADJ       1

# Named Entity Recognition (NER)

In [16]:
import spacy
import re
from spacy import displacy
from spacy import tokenizer

In [17]:
nlp = spacy.load("en_core_web_sm")

In [18]:
google_text = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."
print(google_text)

Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [19]:
spacy_doc = nlp(google_text)

In [20]:
for word in spacy_doc.ents:
    print(word.text, word.label_)

Google ORG
September 4, 1998 DATE
Larry Page PERSON
Sergey Brin PERSON
PhD WORK_OF_ART
Stanford University ORG
California GPE
about 14% PERCENT
56% PERCENT
IPO ORG
2004 DATE
2015 DATE
Google ORG
Alphabet Inc. ORG
Alphabet ORG
Alphabet ORG
Sundar Pichai PERSON
Google ORG
October 24, 2015 DATE
Larry Page PERSON
Alphabet GPE
December 3, 2019 DATE
Pichai PERSON
Alphabet GPE

In [21]:
displacy.render(spacy_doc, style="ent", jupyter=True)

In [22]:
nlp_ua = spacy.load("uk_core_news_sm")

In [23]:
ua_test = """Національний банк України повідомив про зростання обсягів безготівкових розрахунків у першому кварталі 2026 року. За даними регулятора, громадяни все частіше обирають цифрові сервіси для щоденних покупок та оплати комунальних послуг. У Києві, Львові та Одесі частка карткових операцій досягла рекордної позначки в вісімдесят п'ять відсотків.

Голова регулятора Андрій Пишний зазначив, що розширення фінансової інфраструктури залишається пріоритетним завданням для банківської системи. Зокрема, у березні компанія Visa спільно з українськими банками запустила нову програму підтримки малого бізнесу в Полтавській та Чернігівській областях. Проєкт передбачає пільгове встановлення терміналів у сільській місцевості.

Експерти аналітичного центру інвестують значні ресурси у дослідження штучного інтелекту, який допомагає виявляти шахрайські схеми в режимі реального часу. Очікується, що до кінця року обсяг інвестицій у цифрову безпеку зросте на п'ятнадцять мільйонів євро."""

In [24]:
print(ua_test)

Національний банк України повідомив про зростання обсягів безготівкових розрахунків у першому кварталі 2026 року. За даними регулятора, громадяни все частіше обирають цифрові сервіси для щоденних покупок та оплати комунальних послуг. У Києві, Львові та Одесі частка карткових операцій досягла рекордної позначки в вісімдесят п'ять відсотків.

Голова регулятора Андрій Пишний зазначив, що розширення фінансової інфраструктури залишається пріоритетним завданням для банківської системи. Зокрема, у березні компанія Visa спільно з українськими банками запустила нову програму підтримки малого бізнесу в Полтавській та Чернігівській областях. Проєкт передбачає пільгове встановлення терміналів у сільській місцевості.

Експерти аналітичного центру інвестують значні ресурси у дослідження штучного інтелекту, який допомагає виявляти шахрайські схеми в режимі реального часу. Очікується, що до кінця року обсяг інвестицій у цифрову безпеку зросте на п'ятнадцять мільйонів євро.

In [25]:
ua_spacy_doc = nlp_ua(ua_test)

In [26]:
for token in ua_spacy_doc.ents:
    print(token.text, ": ", token.label_)

Національний банк України :  ORG
Києві :  LOC
Львові :  LOC
Одесі :  LOC
Андрій Пишний :  PER
Visa :  ORG
Полтавській та Чернігівській областях :  LOC

In [27]:
displacy.render(ua_spacy_doc, style="ent", jupyter=True)

In [28]:
google_text_clean = re.sub(r"[^\w\s]", "", google_text).lower()

In [29]:
print(google_text_clean)

google was founded on september 4 1998 by computer scientists larry page and sergey brin while they were phd students at stanford university in california together they own about 14 of its publicly listed shares and control 56 of its stockholder voting power through supervoting stock the company went public via an initial public offering ipo in 2004 in 2015 google was reorganized as a wholly owned subsidiary of alphabet inc google is alphabets largest subsidiary and is a holding company for alphabets internet properties and interests sundar pichai was appointed ceo of google on october 24 2015 replacing larry page who became the ceo of alphabet on december 3 2019 pichai also became the ceo of alphabet

In [30]:
spacy_doc_clean = nlp(google_text_clean)

In [31]:
for word in spacy_doc_clean.ents:
    print(word.text, ": ", word.label_)

google :  ORG
september 4 1998 :  DATE
stanford university :  ORG
california :  GPE
about 14 :  CARDINAL
56 :  CARDINAL
2004 :  DATE
2015 :  DATE
alphabet inc google :  ORG
google :  ORG
october 24 2015 :  DATE
larry :  PERSON
december 3 2019 :  DATE

In [32]:
displacy.render(spacy_doc_clean, style="ent", jupyter=True)

# Practical work

In [33]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import spacy
import re
import pandas as pd
import matplotlib.pyplot as plt

## Load data

In [34]:
bbc_data = pd.read_csv("bbc_news.csv")

In [35]:
bbc_data.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [36]:
bbc_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   str
 3   pubDate      1000 non-null   str
 4   guid         1000 non-null   str
 5   link         1000 non-null   str
 6   description  1000 non-null   str
dtypes: int64(2), str(5)
memory usage: 54.8 KB

In [37]:
titles = pd.DataFrame(bbc_data["title"])

In [38]:
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

In [39]:
# lowercase
titles['lowercase'] = titles['title'].str.lower()

In [40]:
# stop words removal
en_stopwords = stopwords.words("english")
titles['no_stopwords'] = titles.apply(lambda s: ' '.join([word for word in s["lowercase"].split() if word not in en_stopwords]), axis=1 )

In [41]:
# punctuation removal
titles['no_stopwords_no_punct'] = titles['no_stopwords'].apply(lambda s: re.sub(r"[^\w\s]", "", s))

In [42]:
# tokenize
titles["tokens_raw"] = titles.apply(lambda s: word_tokenize(s["title"]), axis=1)
titles["tokens_clean"] = titles.apply(lambda s: word_tokenize(s["no_stopwords_no_punct"]), axis=1)

In [43]:
# lemmatizing
lemmatizer = WordNetLemmatizer()
titles['tokens_clean_lemmatized'] = titles['tokens_clean'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])

In [44]:
titles.head(3)

,title,lowercase,no_stopwords,no_stopwords_no_punct,tokens_raw,tokens_clean,tokens_clean_lemmatized
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."

In [45]:
# create lists for just our tokens
tokens_raw_list = sum(titles['tokens_raw'], [])
tokens_clean_list = sum(titles['tokens_clean_lemmatized'], [])

### **POS Tagging**

In [46]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
spacy_doc = nlp(' '.join(tokens_raw_list))

In [ ]:
pos_df = pd.DataFrame(
    columns=['token', 'pos_tag']
)

In [ ]:
for token in spacy_doc:
    pos_df = pd.concat(
        [pos_df, pd.DataFrame.from_records([{"token": token.text, "pos_tag": token.pos_}])], ignore_index=True)

In [135]:
pos_df_counts = pos_df.groupby(["token", "pos_tag"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)

In [136]:
pos_df_counts

          token pos_tag  counts
95            :   PUNCT     543
8             '   PUNCT     300
2897         in     ADP     187
4082         to    PART     175
3268         of     ADP     172
...         ...     ...     ...
2304  crumbling    VERB       1
2305     crunch   PROPN       1
827      Jarrod   PROPN       1
826    Japanese     ADJ       1
0             !   PUNCT       1

[4368 rows x 3 columns]

# **NER**

In [139]:
ner_df = pd.DataFrame(columns=['token', 'ner_tag'])

for token in spacy_doc.ents:
    ner_df = pd.concat(
        [ner_df, pd.DataFrame.from_records([{"token": token.text, "ner_tag": token.label_}])], ignore_index=True
    )

In [141]:
ner_df.head(10)

                                 token   ner_tag
0                            Liz Truss    PERSON
1                                   UK       GPE
2                            Rationing   PRODUCT
3                          superyachts  CARDINAL
4                              Russian      NORP
5                             70 years      DATE
6                           70 seconds      TIME
7                             Red Bull       ORG
8                         Formula 1 's   PRODUCT
9  World Triathlon Championship Series     EVENT

In [143]:
ner_df_counts = ner_df.groupby(["token", "ner_tag"]).size().reset_index(name="counts").sort_values(by="counts", ascending=False)

In [145]:
ner_df_counts.head(10)

               token      ner_tag  counts
965          Ukraine          GPE      47
955               UK          GPE      36
329          England          GPE      32
819          Russian         NORP      20
957               US          GPE      19
1031  World Cup 2022        EVENT      18
1058           first      ORDINAL      13
918       The Papers  WORK_OF_ART      13
378           France          GPE      12
226            China          GPE      11

In [164]:
people = ner_df_counts[ner_df_counts.ner_tag=="PERSON"][:10]

In [165]:
people

             token ner_tag  counts
257          Covid  PERSON       9
760          Queen  PERSON       8
757          Putin  PERSON       8
169  Boris Johnson  PERSON       6
563      Liz Truss  PERSON       6
788    Rishi Sunak  PERSON       5
581         Macron  PERSON       4
762           Quiz  PERSON       4
515   Jurgen Klopp  PERSON       4
325  Emma Raducanu  PERSON       4